name: Build
on: [push]

jobs:
  build-python:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Python environment
      uses: actions/setup-python@v4
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analyze the code with pylint
      run: |
        pylint $(git ls-files '*.py')
    - name: Run python unit tests
      run: |
        python -m unittest discover -s ./tests/helpers -p "*_tests.py"
    
  build-nodejs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui/da-app
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Nodejs environment
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install npm packages
      # run: cd ./ui/da-app && npm install
      run: npm install
    - name: Run lint
      # run: cd ./ui/da-app && npm run lint
      run: npm run lint
    - name: Build nextjs
      run: npm run build
